// GENERATED by analysis/thermal/fit_surface_model.py -- do not edit by hand.
// Re-run the fit and regenerate whenever the DS18B20, LED array or heater is
// remounted: this table describes the geometry it was measured on.
//
// model id : 20260917-p01s01
// sources  : aligned_tpbm_temperature_p01_s01_1789674935519__thermistor_20260917T195501_925141Z.csv
// LED      : n=1706, RMS 0.59 C, worst 2.3 C, residual -2.3..+2.1 C
// HEATER   : n=563, RMS 0.21 C, worst 0.9 C
//
// surface = device + gap[device] + rate * (device - device_40s_ago) / 40
#ifndef SURFACE_MODEL_H
#define SURFACE_MODEL_H

#define SURF_MODEL_ID      "20260917-p01s01"
#define SURF_SLOPE_WINDOW_S 40
#define SURF_NODE_T0       16.0f
#define SURF_NODE_STEP     2.0f
#define SURF_NODE_N        16

// gap (surface minus device, C) at zero slope, at device temperatures
// 16, 18, ... 46 C; flat beyond the ends.
const float SURF_GAP_LED[SURF_NODE_N]    = {3.822f, 3.822f, 3.822f, 3.282f, 3.090f, 2.723f, 2.921f, 2.983f, 2.699f, 2.391f, 1.776f, 1.776f, 1.776f, 1.776f, 1.776f, 1.776f};
const float SURF_RATE_LED                = 97.19f;   // C per (C/s) of device slope
const float SURF_GAP_HEATER[SURF_NODE_N] = {3.628f, 3.628f, 3.628f, 3.628f, 3.628f, 1.241f, 1.241f, 1.241f, 1.241f, 1.241f, 1.241f, 1.241f, 1.241f, 1.241f, 1.241f, 1.241f};
const float SURF_RATE_HEATER             = 46.75f;

#endif
